version: '3.7'

services:
    userapi:
        image: creativ360/development:covidscreener_userapi1.0
        deploy:
            replicas: 1
        restart: unless-stopped
        stop_grace_period: 2m
        expose:
            - '8080'
        networks:
            screener:
networks:
    screener:
        external:
            name: covidscreener-network
