version: '3.7'

services:
    excelintegrationservice:
        image: creativ360/development:excelintegrationservice1.0
        deploy:
            replicas: 1
        restart: unless-stopped
        stop_grace_period: 2m
        networks:
            screener:
networks:
    screener:
        external:
            name: covidscreener-network
