version: '3.7'

services:
    client:
        image: creativ360/development:covidscreener_client1.0
        deploy:
            replicas: 1
        restart: unless-stopped
        stop_grace_period: 2m
        ports:
            - '8008:80'
