version: '3.7'

services:
    payfastapi:
        image: creativ360/development:covidscreener_payfastapi1.0
        deploy:
            replicas: 1
        restart: unless-stopped
        stop_grace_period: 2m
        expose:
            - '8080'
        environment: 
            environment: development
        networks:
            screener:
networks:
    screener:
        external:
            name: covidscreener-network
