version: '3.7'

services:
    excelintegrationapi:
        image: creativ360/development:excelintegrationapi1.0
        deploy:
            replicas: 1
        restart: unless-stopped
        stop_grace_period: 2m
        ports:
            - 'XXXX:8080'
        networks:
            screener:
networks:
    screener:
        external:
            name: covidscreener-network
